name: 'jira2md'
description: 'A GitHub action to convert between Jira text formatting and GitHub flavored markdown'
inputs:
  input-text:
    description: 'The input text to convert'
    required: true
  mode:
    description: 'The conversion mode; `jira2md`, `md2jira`, `md2html` or `jira2html`'
    default: jira2md
outputs:
  output-text:
    description: 'The converted text'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'activity'
  color: 'blue'
